### ISSUE TITLE
Have precipitation extremes and annual totals been increasing in the world’s dry regions over the last 60 years?

### ISSUE THREAD

**Issue by LG-cyber** [o2r-project/erc-examples#12]
- [x] figures have caption (some papers have headlines, some have the beginning of a headline, some have captions, some do not have anything) 
- [x] when manipulating figures, orange and light blue lines are often not inside the window size (e.g. 3 and 4)
- [x] header "nref" could maybe be a whole sentence
- [ ] figure 1B does not react to manipulation, also "save for comparison" can only be clicked once, no second setting can be saved for comparison. 
- [x] warning=F is twice in rmd setting
- [x] Image build takes very long (10-15 min)

**Comment by MarkusKonk** [comment]
"figure 1B does not react to manipulation, also "save for comparison" can only be clicked once, no second setting can be saved for comparison."
--> platform issue
