### ISSUE TITLE
A question driven socio-hydrological modeling process

### ISSUE THREAD

**Issue by LG-cyber** [o2r-project/erc-examples#22]
- [x] when manipulating, it is possible to click onto "original settings". The figure changes its settings to KP=1, but the selection (1,2,3) stays at KP=3 or KP=2 and does not switch to KP=1. 
- [x] the differences should only be the dotted lines, in the figure on the top right hand side the original line changes as well. Is that on purpose?

**Comment by MarkusKonk** [comment]
@LG-cyber regarding the second purpose: This just because of a shift in the scale
