### ISSUE TITLE
Tidy_data

### ISSUE THREAD

**Issue by LG-cyber** [o2r-project/erc-examples#4]
- [x] affiliation is "RStudio"
- [x] data "deaths08.csv" is located in subfolder "deaths08.csv.bz2" and cannot be inspected on platform (no subfolder needed?)
- [x] warning=F exist twice in rmd setting 
- [x] Fig. 1-3 have the same text above manipulation "The filter parameter creates a subset of the dataset." as well as 4A&4B "The costrain parameter creates a subset of the dataset."
- [x] add caption from the paper to the figures in HTML
- [x] rerun analysis locally and replace display.html
- [x] rerun analysis on platform and update sheet: https://docs.google.com/spreadsheets/d/1WG8Ab5EKhb4KcZNLpveWwbvqlZ41Gjj7l1LccKyBla4/edit#gid=941422441

**Comment by MarkusKonk** [comment]
bzgl. deaths08.csv: Right, but the dataset is too large to show it on our platform
