### ISSUE TITLE
Technical note: Fourier approach for estimating the thermal attributes of streams

### ISSUE THREAD

**Issue by LG-cyber** [o2r-project/erc-examples#8]
- [x] publication date is not correct 
- [x] warnings=F is twice in rmd setting
- [x] in html: "Figure 2: Figure2. ..." (delete the whole line as it is not the complete caption and figures do not get headers?)
- [x] "Figure 2"-text is also a problem within the Reproducibility check 
- [x]  Manipulate: "Note: threshold can be arbitrary, try different values and visually evaluate from figures, a recommendation is to set it firstly to the value of minimum unit of measurement."
for a better understanding I would suggest "...visually evaluate from figures. As a recommendation: First set the value to the smallest possible unit" (I do not really get what needs to be done first, so my suggestion is probably wrong.)
- [x] when manipulating: Fig. 2A: 0.1 is different from 1.0 but everything in between is the same as the 1.0-figure. All the steps on the slider in between the two extremes do not vary from 1.0 setting.
- [x] when manipulating: Fig 2B: 0.1-0.2 is good, 0.3-0.5 is just a red screen and from 0.6-1.0 there are no differences even though the settings were changed.

**Comment by MarkusKonk** [comment]
Good points that you mentioned, particularly regarding the manipulation of 2a/b. I changed and it makes more sense now.
